/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HivePdfViewer {
    'src': string | Uint8Array;
  }
  interface HivePdfViewerAttributes extends StencilHTMLAttributes {
    'onPageChange'?: (event: CustomEvent<number>) => void;
    'src'?: string | Uint8Array;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HivePdfViewer': Components.HivePdfViewer;
  }

  interface StencilIntrinsicElements {
    'hive-pdf-viewer': Components.HivePdfViewerAttributes;
  }


  interface HTMLHivePdfViewerElement extends Components.HivePdfViewer, HTMLStencilElement {}
  var HTMLHivePdfViewerElement: {
    prototype: HTMLHivePdfViewerElement;
    new (): HTMLHivePdfViewerElement;
  };

  interface HTMLElementTagNameMap {
    'hive-pdf-viewer': HTMLHivePdfViewerElement
  }

  interface ElementTagNameMap {
    'hive-pdf-viewer': HTMLHivePdfViewerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
